# Generated by Django 5.0.1 on 2024-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
