# Generated by Django 5.0.1 on 2024-01-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_doctor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
