# Generated by Django 5.0.1 on 2024-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_doctor_timing1_doctor_timing2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='timing1',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='timing2',
            field=models.TimeField(default='17:00'),
        ),
    ]
