# Generated by Django 5.0.1 on 2024-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_doctor_timing1_alter_doctor_timing2'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timing1',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timing2',
            field=models.TimeField(default='17:00'),
        ),
    ]
