# Generated by Django 5.0.1 on 2024-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_appointment_timing1_appointment_timing2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Neurology', 'Neurology'), ('Orthopaedic', 'Orthopaedic'), ('Urology', 'Urology'), ('MD', 'MD')], default='Cardiologist', max_length=50),
        ),
    ]
