# Generated by Django 5.0.1 on 2024-04-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='isDischarged',
            field=models.BooleanField(default=False),
        ),
    ]
