# Generated by Django 5.0.1 on 2024-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_patientdischargedetails_isdischarged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='isDischarged',
        ),
        migrations.AddField(
            model_name='patient',
            name='isDischarged',
            field=models.BooleanField(default=False),
        ),
    ]
