# Generated by Django 5.0.1 on 2024-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_remove_patientdischargedetails_isdischarged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='isAppointed',
            field=models.BooleanField(default=False),
        ),
    ]
