# Generated by Django 5.0.1 on 2024-04-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
